declare module "@alpinejs/focus";
declare module "@alpinejs/intersect";
declare module "@alpinejs/collapse";
declare module "alpinejs-textarea-grow";
declare module "lazysizes/plugins/bgset/ls.bgset";
declare module "lazysizes/plugins/parent-fit/ls.parent-fit";
declare module "lazysizes/plugins/aspectratio/ls.aspectratio";
declare module "lazysizes/plugins/native-loading/ls.native-loading";
declare module "lazysizes";
