Neos:
  Neos:
    fusion:
      autoInclude:
        Litefyr.Presentation: true
    userInterface:
      translation:
        autoInclude:
          Litefyr.Presentation:
            - 'Spacing'
  Fusion:
    defaultContext:
      Presentation: 'Litefyr\Presentation\EelHelper\PresentationHelper'
