Neos:
  Neos:
    fusion:
      autoInclude:
        Litespeed.Presentation: true
    userInterface:
      translation:
        autoInclude:
          Litespeed.Presentation:
            - 'Spacing'
  Fusion:
    defaultContext:
      Presentation: 'Litespeed\Presentation\EelHelper\PresentationHelper'
