Neos:
  Neos:
    Ui:
      resources:
        javascript:
          Litefyr.Presentation:
            resource: resource://Litefyr.Presentation/Public/Scripts/UiHelper.js
    fusion:
      autoInclude:
        Litefyr.Presentation: true
    userInterface:
      translation:
        autoInclude:
          Litefyr.Presentation:
            - 'Spacing'
  Fusion:
    defaultContext:
      Presentation: 'Litefyr\Presentation\EelHelper\PresentationHelper'
